### ISSUE TITLE
admin process occupies cpu 100%

### ISSUE THREAD

**Issue by HQidea** [node-honeycomb/honeycomb-server#38]
这个问题有多个现象：

1. cpu一个核心利用率100%（一定有）
2. `__ADMIN__`进程占用cpu 100%（这个可能有，可能无）
3. 9999端口有数百个CLOSE_WAIT（这个可能有，可能无）

**Comment by fishbar** [comment]
目前主要的怀疑还是文件系统的问题，接口没发现可能存在的死循环逻辑

**Comment by fishbar** [comment]
非代码问题

归到系统日志文件问题上，之前在日志目录的mount操作，导致日志文件出现异常，读取会引起该问题。
