### ISSUE TITLE
it's not supposed to throw certain error here

### ISSUE THREAD

**Issue by cctv1005s** [node-honeycomb/honeycomb-server#49]
once I  use this code below

``
 require.solve('~/index.js');
``

the error is not that the 'main' property can not be found.

https://github.com/node-honeycomb/honeycomb-server/blob/baa16561f7ecad833db7ae7bbe7232040e1c41ae/lib/master.js#L199-L203

**Comment by fishbar** [comment]
文案需要优化一下，你这属于人肉入侵了， dir通常都指向到 app的解压目录，所以之前的文案是这么提示的
