### ISSUE TITLE
crontab变更

### ISSUE THREAD

**Issue by backsapce** [node-honeycomb/honeycomb-server#86]
1. RPM包Requires增加cronie，包含了crontab以及执行cron任务的必要程序
2. rpm post阶段插入crontab任务
```shell
# begin crontab
if grep -q crontab_clear_logs /var/spool/cron/admin; then
  echo "crontab already inited";
else
  echo "install crontab jobs"
  echo '30 2 * * * /home/admin/honeycomb/bin/crontab_clear_logs > /dev/null 2>&1' > /var/spool/cron/admin
  echo '30 2 * * * /home/admin/nginx/sbin/nginx_clean_log > /dev/null 2>&1' >> /var/spool/cron/admin
fi
```
3. 增加crontab_clear_logs和nginx_clearn_log脚本用于定期清除日志
[变更记录](https://github.com/node-honeycomb/honeycomb-server-rpm/commit/5f89671f74335210b243a1df09c205aca6301a23)

**Comment by fishbar** [comment]
这个crontab任务自己的日志，也需要留意一下，也会爆炸，比如在嵌入小型设备上
