### ISSUE TITLE
free memory bug

### ISSUE THREAD

**Issue by cctv1005s** [node-honeycomb/honeycomb-server#96]
https://github.com/node-honeycomb/honeycomb-server/blob/e5f31711bceac04a6fb038eae38729621d7b89de/lib/admin/single_api/system.js#L12

free memory 这个包有问题，这个包利用系统的free命令切割字符串来判断系统内存的，在中文系统上的机器不可使用，会造成admin进程退出，推荐使用`os.freemem()`来计算空闲内存

**Comment by fishbar** [comment]
os.freemem() 计算不准确，语言问题，这个需要寻找更好的替代包
